apiVersion: v2
name: readarr
description: A fork of Radarr to work with Musics
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/readarr
icon: https://readarr.com/img/logo.png
sources:
  - https://github.com/Readarr/Readarr
  - https://github.com/k8s-at-home/container-images
dependencies:
  - name: readarr
    repository: https://k8s-at-home.com/charts/
    version: 6.4.2

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 6.4.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.4.11.2747"

keywords:
  - readarr
  - torrent
  - usenet
  - AudioBooks
  - ebooks
